name: CI Build for Centurionhms Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sign in to Droplet and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |

            cd /home

            cd EkoXchangeAdmin

            git pull

            docker stop admin-web
            docker rm admin-web
            docker rmi ekoxchange-admin:latest || true

            docker build -t ekoxchange-admin:latest .
            docker run -d --name admin-web -p 3001:3001 ekoxchange-admin:latest
            

        # continue-on-error: true  # This will allow the job to continue even if this step fails

